# @package _global_

# conf/variant/htdemucs_repro.yaml
model: htdemucs
segment: 5
precision: fp16
batch_size: 1

dset:
  musdb: /mnt/data/xxn/data/musdbhq

htdemucs:
  channels: 512
  depth: 5
  kernel_size: 8
  t_layers: 6
  t_heads: 8
  t_hidden_scale: 4.0

augment:
  shift_same: false
  repitch:
    proba: 0
    max_tempo: 12
  remix:
    proba: 0
    group_size: 4
  scale:
    proba: 0
    min: 0.25
    max: 1.25
  flip: false


